### ISSUE TITLE
Convert index.html to fit HCP

### ISSUE THREAD

**Issue by quiquee** [hcpch/WebHCP#1]

**Comment by felipesanti** [comment]
Me encanta verte en GitHub!!!

**Comment by quiquee** [comment]
jajaja

**Comment by quiquee** [comment]
Done from scratch using a theme downloaded from https://bootstrapmade.com/squadfree-free-bootstrap-template-creative/

Published in the master branch and exposed as GitHub page with custom domain: hcpartners.ch and www.hcpartners.ch . 

Connections to helvetiaconsultingpartners.* will be redirected to http://www.hcpartners.ch

Secure connections have to go to https://www.helvetiaconsultingpartners.ch or https://helvetiaconsultingpartners.ch , that are the hostnames for which we have certificate from godaddy

DNS Records are as follows:

SOA Record
Domain	Seriennummer	E-Mail	Primärer Nameserver	Bearbeiten
hcpartners.ch	2017032605	enrique.melero@gmail.com	ns1.dns-zonen.ch	Bearbeiten
A Record
Host	IPv4-Adresse	TTL	Bearbeiten	Löschen
*.hcpartners.ch	176.28.53.255	10800	Bearbeiten	Löschen
hcpartners.ch	192.30.252.153	10800	Bearbeiten	Löschen
www.hcpartners.ch	192.30.252.153	10800	Bearbeiten	Löschen

AAAA Record
Host	IPv6-Adresse	TTL	Bearbeiten	Löschen

CNAME Record
Host	Canonical Name	TTL	Bearbeiten	Löschen

MX Record
Host	Mail Exchanger	Präferenz	TTL	Bearbeiten	Löschen
hcpartners.ch	mail.helvetiaconsultingpartners.ch	10	10800	Bearbeiten	Löschen

NS Record
Host	Nameserver	TTL	Bearbeiten	Löschen
hcpartners.ch	ns3.dns-zonen.ch	10800	nicht verfügbar	nicht verfügbar
hcpartners.ch	ns2.dns-zonen.ch	10800	nicht verfügbar	nicht verfügbar
hcpartners.ch	ns1.dns-zonen.ch	10800	nicht verfügbar	nicht verfügbar
