### ISSUE TITLE
Remove contact form

### ISSUE THREAD

**Issue by felipesanti** [hcpch/WebHCP#4]
Remove contact form, which does not work anyway with github pages.
Add instead:
- link to our emails in the partners photos (add <a> html tag)
- link to the info email in the contact section, maybe adding a "CONTACT US" call to action button or similar (see web sismotur, it works!)

**Comment by quiquee** [comment]
Done in commits:
- https://github.com/hcpch/WebHCP/commit/a8c77c1b01c7ca265e7ae070ab89acc20a78dd0a
- https://github.com/hcpch/WebHCP/commit/64cd26f19093246f0c1f378a15ff8eb56e97a2be
